name: talklynk_sdk
description: A Flutter SDK for TalkLynk real-time communication platform
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # WebRTC for video/audio
  flutter_webrtc: ^0.9.36
  
  # WebSocket communication
  web_socket_channel: ^2.4.0
  
  # HTTP requests
  http: ^1.1.0
  
  # Logging
  logger: ^2.0.2
  
  # Permissions for camera/microphone
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true